# Generated by Django 2.1.4 on 2019-01-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boards.Question'),
        ),
    ]
